# Minimal linting configuration - disables most suggestions
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat all lints as info instead of warnings
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: info
    prefer_const_literals_to_create_immutables: info
    prefer_final_fields: info
    prefer_final_in_for_each: info
    prefer_final_locals: info
    use_key_in_widget_constructors: info

linter:
  rules:
    # Disable ALL const-related suggestions
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    
    # Disable final field suggestions
    prefer_final_fields: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    
    # Disable widget constructor suggestions
    use_key_in_widget_constructors: false
    
    # Disable other annoying suggestions
    avoid_redundant_argument_values: false
    avoid_unnecessary_containers: false
    sized_box_for_whitespace: false
    
    # Keep only critical rules
    avoid_print: false
    prefer_single_quotes: true